### ISSUE TITLE
Board Templates

### ISSUE THREAD

**Issue by kmccullen97** [kmccullen97/terminal-kanban#23]
Allow a user to configure and select from a list of board templates when creating a new board.

Example
```
┌─New Board──────────────────────────────┐
│                                        │
│ Name: Example Board                    │
│                                        │
│ Template: 1                            │
│                       1. Default       │
│                       2. Blank         │
│                       2. Custom        │
│                                        │
│                              Cancel Ok │
└────────────────────────────────────────┘
```

Users can override the board templates with custom templates in their `config.yml` file...
```yaml
board_templates:
  default:
    cols:
    - To Do
    - Doning
    - Done
  blank:
    cols: []
  My Custom Template:
    cols:
    - Col 1
    - Col 2
    - Col 3
    - Col 4
```
